/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
FilterAudioProcessorEditor::FilterAudioProcessorEditor (FilterAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter),
    slider("Flange")
{
    // This is where our plugin's editor size is set.
    setSize (400, 100);
    addAndMakeVisible(slider);
    slider.setSliderStyle(Slider::Rotary);
    slider.addListener(this);
    slider.setRange(0.00, 0.20, 0.001);
}

FilterAudioProcessorEditor::~FilterAudioProcessorEditor()
{
}

//==============================================================================
void FilterAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::grey);
}

void FilterAudioProcessorEditor::resized() {
   slider.setBounds(0, 0, 400, 100);
}

void FilterAudioProcessorEditor::sliderValueChanged(Slider* s) {
   updateFlangeSpeed(slider.getValue());
}